static VERSIONS_PRE_5_0: &[&str] = &["4.2", "4.4"];
static VERSIONS_5_0_PLUS: &[&str] = &["5.0", "6.0", "7.0", "8.0", "9.0", "rapid", "latest"];
fn all_versions() -> impl Iterator<Item = &'static &'static str> {
    VERSIONS_PRE_5_0.iter().chain(VERSIONS_5_0_PLUS)
}

static SERVER: &str = "server";
static REPLICA_SET: &str = "replica_set";
static SHARDED_CLUSTER: &str = "sharded_cluster";
static TOPOLOGIES: &[(&str, &str)] = &[
    ("standalone", SERVER),
    ("replicaset", REPLICA_SET),
    ("sharded", SHARDED_CLUSTER),
];

static HEADER: &str = "# Generated by generate-tasks. Do not manually edit!\n\ntasks:";

fn main() {
    // this is only run locally to generate tasks
    // nosemgrep: rust.lang.security.args.args
    let mut args = std::env::args().skip(1);

    let suite = args.next();
    if !args.next().is_none() {
        eprintln!("A maximum of one suite can be specified per run");
    }

    match suite.as_deref() {
        Some("driver-tests") => driver_tests(),
        Some("in-use-encryption") => in_use_encryption(),
        Some("load-balancer") => load_balancer(),
        Some(other) => eprintln!("Suite {other} not recognized"),
        None => eprintln!("Test suite to generate not specified"),
    }
}

fn driver_tests() {
    println!("{HEADER}");
    for (top_name, topology) in TOPOLOGIES.iter() {
        for version in all_versions() {
            println!(
                "
  - name: test-{version}-{top_name}
    tags: [{version}, {top_name}]
    depends_on:
      - name: build-nextest-archive
        patch_optional: true
    commands:
      - func: fetch nextest archive
      - func: bootstrap mongo-orchestration
        type: setup
        vars:
          MONGODB_VERSION: {version}
          TOPOLOGY: {topology}
      - func: run driver test suite"
            );
        }
    }
}

fn in_use_encryption() {
    println!("{HEADER}");
    for version in all_versions() {
        println!(
            "
  - name: test-in-use-encryption-{version}
    tags: [in-use-encryption]
    depends_on:
      - name: build-nextest-archive
    commands:
      - func: fetch nextest archive
      - func: install libmongocrypt
      - func: bootstrap mongo-orchestration
        type: setup
        vars:
          MONGODB_VERSION: {version}
          TOPOLOGY: {REPLICA_SET}
      - func: start csfle servers
      - func: run csfle tests"
        );
    }
}

fn load_balancer() {
    println!("{HEADER}");
    for version in VERSIONS_5_0_PLUS {
        println!(
            "
  - name: test-load-balancer-{version}
    tags: [load-balancer]
    depends_on:
      - name: build-nextest-archive
    commands:
      - func: fetch nextest archive
      - func: bootstrap mongo-orchestration
        type: setup
        vars:
          MONGODB_VERSION: {version}
          TOPOLOGY: {SHARDED_CLUSTER}
          LOAD_BALANCER: true
      - func: start load balancer
      - func: run driver test suite"
        );
    }
}
