############################################################
# Evergreen configuration file for the MongoDB Rust Driver #
############################################################

# If a task fails, go through all versions that may have been skipped to detect when it started
# failing.
stepback: true

# Mark a failure as a system failure (purple) rather than a test failure (red) by default. To
# override this for tests, mark the function as type: test.
command_type: system

# If any of the pre tasks fails, the task will be marked as a failure.
pre_error_fails_task: true

include:
  - filename: .evergreen/util.yml
  - filename: .evergreen/configs/driver-tests.yml
  - filename: .evergreen/configs/load-balancer.yml
  - filename: .evergreen/configs/in-use-encryption.yml
  - filename: .evergreen/configs/checks.yml
  - filename: .evergreen/configs/compression.yml
  - filename: .evergreen/configs/aws-auth.yml
  - filename: .evergreen/configs/oidc.yml
  - filename: .evergreen/configs/kms.yml
  - filename: .evergreen/configs/atlas.yml
  - filename: .evergreen/configs/other-auth.yml
  - filename: .evergreen/configs/happy-eyeballs.yml
  - filename: .evergreen/configs/aws-lambda.yml
  - filename: .evergreen/configs/misc-tests.yml

# Functions to run before all tasks (except those in task groups).
pre:
  - func: "fetch source"
  - func: "create expansions"
  - func: "prepare resources"
  - func: "windows fix"
  - func: "fix absolute paths"
  - func: "init test-results"
  - func: "make files executable"
  - func: "install rust"
  - func: "install junit dependencies"

# Functions to run after all tasks (except those in task groups).
post:
  - func: "stop load balancer"
  - func: "stop mongo orchestration"
  - func: "tear down aws"
  - func: "upload test results"
  - func: "upload-mo-artifacts"
  - func: "cleanup"

# Cause a timeout if a task does not complete within 150 minutes. TODO RUST-1721: reduce this.
exec_timeout_secs: 9000
# What to do if the timeout is hit. Post-task functions will still run.
timeout:
  - command: shell.exec
    params:
      script: |
        ls -la

##################
# Build Variants #
##################
buildvariants:
  - name: compile
    display_name: "Compile Only"
    run_on:
      - rhel8-latest-small
    tasks:
      - name: compile-on-latest
      - name: compile-on-msrv

  - name: lint
    display_name: "Lint"
    run_on:
      - ubuntu2404-small
    expansions:
      LIBMONGOCRYPT: true
    tasks:
      - name: .lint

  - name: cargo-deny
    display_name: "Cargo Deny"
    run_on:
      - rhel8-latest-small
    tasks:
      - name: check-cargo-deny

  - name: rhel-8
    display_name: "RHEL 8"
    run_on:
      - rhel8-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .standalone
      - name: .replicaset
      - name: .sharded

  - name: ubuntu-22.04-arm64
    display_name: "Ubuntu 22.04 (ARM64)"
    run_on:
      - ubuntu2204-arm64-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      # Ubuntu 22.04 does not support MongoDB versions below 6.0.
      - name: .standalone !.4.4 !.5.0
      - name: .replicaset !.4.4 !.5.0
      - name: .sharded !.4.4 !.5.0

  - name: macos-14.00
    display_name: "MacOS 14.00"
    run_on:
      - macos-14
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .standalone
      - name: .replicaset
      - name: .sharded

  - name: windows-2022
    display_name: "Windows 2022"
    run_on:
      - windows-2022-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .standalone
      - name: .replicaset
      - name: .sharded

  - name: openssl-rhel
    display_name: "OpenSSL (RHEL)"
    run_on:
      - rhel8-latest-small
    expansions:
      OPENSSL: true
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .rapid .replicaset

  - name: openssl-ubuntu
    display_name: "OpenSSL (Ubuntu)"
    # patchable: false
    run_on:
      - ubuntu2204-arm64-small
    expansions:
      OPENSSL: true
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .rapid .replicaset

  - name: openssl-macos
    display_name: "OpenSSL (MacOS)"
    # patchable: false
    run_on:
      - macos-14
    expansions:
      OPENSSL: true
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .rapid .replicaset

  - name: openssl-windows
    display_name: "OpenSSL (Windows)"
    # patchable: false
    run_on:
      - windows-2022-latest-small
    expansions:
      OPENSSL: true
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - name: .rapid .replicaset

  - name: no-auth-tls
    display_name: "No Auth/TLS"
    run_on:
      - rhel8-latest-small
    tasks:
      - name: build-nextest-archive
      - .rapid .replicaset

  - name: compression
    display_name: "Compression"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - .compression

  - name: stable-api
    display_name: "Stable API V1"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      REQUIRE_API_VERSION: true
      MONGODB_API_VERSION: 1
      AUTH: auth
      # Configuring SSL: ssl causes errors in bootstrap mongo-orchestration.
    tasks:
      - name: build-nextest-archive
      # The Stable API was introduced in MongoDB version 5.0. Drivers Evergreen Tools only supports
      # setting REQUIRE_API_VERSION on standalones and sharded clusters.
      - .standalone !.4.4
      - .sharded !.4.4

  - name: sync-api
    display_name: "Sync API"
    run_on:
      - rhel8-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - .sync

  - name: atlas-connectivity
    display_name: "Atlas Connectivity"
    # patchable: false
    run_on:
      - rhel8-latest-small
    tasks:
      - .atlas

  - name: aws-auth
    display_name: "AWS Authentication"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      ORCHESTRATION_FILE: auth-aws.json
    tasks:
      - .aws-auth !test-aws-auth-ecs

  - name: aws-auth-ecs
    display_name: "AWS Authentication (ECS)"
    # patchable: false
    run_on:
      - ubuntu2404-small
    expansions:
      ORCHESTRATION_FILE: auth-aws.json
    tasks:
      - test-aws-auth-ecs

  - name: azure-kms
    display_name: "Azure KMS"
    # patchable: false
    run_on:
      # The Azure CLI is not available on RHEL/Ubuntu machines.
      - debian11-small
    expansions:
      LIBMONGOCRYPT: true
    tasks:
      - name: azure-kms-task-group
    # Limit the test to only schedule every 14 days to reduce external resource usage.
    batchtime: 20160

  - name: gcp-kms
    display_name: "GCP KMS"
    # patchable: false
    run_on:
      # The GCP CLI is not available on RHEL/Ubuntu machines.
      - debian11-small
    expansions:
      LIBMONGOCRYPT: true
    tasks:
      - name: gcp-kms-task-group
    # Limit the test to only schedule every 14 days to reduce external resource usage.
    batchtime: 20160

  - name: gssapi-auth-linux
    display_name: "GSSAPI Authentication - Linux"
    patchable: false
    disable: true
    run_on:
      - rhel8-latest-small
    tasks:
      - test-gssapi-auth

  - name: gssapi-auth-macos
    display_name: "GSSAPI Authentication - macOS"
    patchable: false
    disable: true
    run_on:
      - macos-14
    tasks:
      - test-gssapi-auth

  - name: gssapi-auth-windows
    display_name: "GSSAPI Authentication - Windows"
    patchable: false
    disable: true
    run_on:
      - windows-2022-latest-small
    tasks:
      - test-gssapi-auth

  - name: x509-auth
    display_name: "x509 Authentication"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - name: test-x509-auth

  - name: plain-auth
    display_name: "PLAIN Authentication"
    patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks: test-plain-auth

  - name: oidc-linux
    display_name: "OIDC Linux"
    patchable: true
    run_on:
      - ubuntu2204-large
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - test-oidc-task-group
      - test-azure-oidc-task-group
      - test-gcp-oidc-task-group
      - test-k8s-oidc-task-group

  - name: oidc-macos
    display_name: "OIDC MacOS"
    patchable: true
    run_on:
      - macos-14
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - test-oidc-task-group

  - name: oidc-windows
    disable: true
    display_name: "OIDC Windows"
    patchable: true
    run_on:
      - windows-2022-latest-small
    expansions:
      AUTH: auth
      SSL: ssl
    tasks:
      - test-oidc-task-group
      - test-azure-oidc-task-group
      - test-gcp-oidc-task-group

  - name: in-use-encryption
    display_name: "In-Use Encryption"
    run_on:
      - rhel8-latest-small
    expansions:
      LIBMONGOCRYPT: true
      AUTH: auth
      SSL: ssl
    tasks:
      - name: build-nextest-archive
      - .in-use-encryption

  - name: in-use-encryption-disable-crypt-shared
    display_name: "In-Use Encryption (disable crypt_shared)"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      LIBMONGOCRYPT: true
      AUTH: auth
      SSL: ssl
      DISABLE_CRYPT_SHARED: true
    tasks:
      - name: build-nextest-archive
      - .in-use-encryption

  - name: in-use-encryption-openssl
    display_name: "In-Use Encryption (OpenSSL)"
    run_on:
      - rhel8-latest-small
    expansions:
      LIBMONGOCRYPT: true
      AUTH: auth
      SSL: ssl
      OPENSSL: true
    tasks:
      - name: build-nextest-archive
      - test-in-use-encryption-rapid

  - name: load-balancer
    display_name: "Load Balancer"
    run_on:
      - rhel8-latest-small
    tasks:
      - name: build-nextest-archive
      - .load-balancer

  - name: search-index
    display_name: "Search Index Helpers"
    # patchable: false
    run_on:
      - rhel8-latest-small
    tasks:
      - name: search-index-task-group

  - name: aws-lambda
    display_name: "AWS Lambda"
    # patchable: false
    run_on:
      - rhel8-latest-small
    tasks:
      - name: test-aws-lambda-task-group

  - name: happy-eyeballs-macos
    display_name: "Happy Eyeballs (MacOS)"
    # patchable: false
    run_on:
      - macos-14
    tasks:
      - happy-eyeballs-task-group

  - name: socks5-proxy-no-tls
    display_name: "SOCKS5 Proxy (No TLS)"
    # patchable: false
    run_on:
      - rhel8-latest-small
    tasks:
      - test-socks5-proxy

  - name: socks5-proxy-tls
    display_name: "SOCKS5 Proxy (TLS)"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      SSL: ssl
    tasks:
      - test-socks5-proxy

  - name: socks5-proxy-openssl
    display_name: "SOCKS5 Proxy (OpenSSL)"
    # patchable: false
    run_on:
      - rhel8-latest-small
    expansions:
      SSL: ssl
      OPENSSL: true
    tasks:
      - test-socks5-proxy

  #- name: graviton-legacy
  #  display_name: "Graviton (legacy versions)"
  #  run_on:
  #    - amazon2-arm64-latest-large-m8g
  #  tasks:
  #    - name: .6.0
  #    - name: .5.0
  #    - name: .4.4
  #    - name: .4.4

  - name: graviton
    display_name: "Graviton"
    run_on:
      - amazon2023-arm64-latest-large-m8g
    tasks:
      - name: build-nextest-archive
      - name: .latest
      #- name: .8.0
      #- name: .7.0

  - name: bevy
    display_name: "Bevy"
    # patchable: false
    run_on: [rhel8-latest-small]
    tasks:
      - name: test-bevy-asset
