//! This file was autogenerated.  Do not manually edit.
use super::*;
#[allow(missing_docs)]
pub struct Autocomplete;
impl AtlasSearch<Autocomplete> {
    /**The autocomplete operator performs a search for a word or phrase that
    contains a sequence of characters from an incomplete input string. The
    fields that you intend to query with the autocomplete operator must be
    indexed with the autocomplete data type in the collection's index definition.
    */
    ///
    ///For more details, see the [autocomplete operator reference](https://www.mongodb.com/docs/atlas/atlas-search/autocomplete/).
    pub fn autocomplete(path: impl StringOrArray, query: impl StringOrArray) -> Self {
        AtlasSearch {
            name: "autocomplete",
            stage: doc! {
                "path" : path.to_bson(), "query" : query.to_bson(),
            },
            _t: PhantomData,
        }
    }
    #[allow(missing_docs)]
    pub fn token_order(mut self, token_order: TokenOrder) -> Self {
        self.stage.insert("tokenOrder", token_order.name());
        self
    }
    #[allow(missing_docs)]
    pub fn fuzzy(mut self, fuzzy: Document) -> Self {
        self.stage.insert("fuzzy", fuzzy);
        self
    }
    #[allow(missing_docs)]
    pub fn score(mut self, score: Document) -> Self {
        self.stage.insert("score", score);
        self
    }
}
#[allow(missing_docs)]
pub struct Text;
impl AtlasSearch<Text> {
    /**The text operator performs a full-text search using the analyzer that you specify in the index configuration.
    If you omit an analyzer, the text operator uses the default standard analyzer.
    */
    ///
    ///For more details, see the [text operator reference](https://www.mongodb.com/docs/atlas/atlas-search/text/).
    pub fn text(path: impl StringOrArray, query: impl StringOrArray) -> Self {
        AtlasSearch {
            name: "text",
            stage: doc! {
                "path" : path.to_bson(), "query" : query.to_bson(),
            },
            _t: PhantomData,
        }
    }
    #[allow(missing_docs)]
    pub fn fuzzy(mut self, fuzzy: Document) -> Self {
        self.stage.insert("fuzzy", fuzzy);
        self
    }
    #[allow(missing_docs)]
    pub fn match_criteria(mut self, match_criteria: MatchCriteria) -> Self {
        self.stage.insert("matchCriteria", match_criteria.name());
        self
    }
    #[allow(missing_docs)]
    pub fn synonyms(mut self, synonyms: impl AsRef<str>) -> Self {
        self.stage.insert("synonyms", synonyms.as_ref());
        self
    }
    #[allow(missing_docs)]
    pub fn score(mut self, score: Document) -> Self {
        self.stage.insert("score", score);
        self
    }
}
#[allow(missing_docs)]
pub struct Compound;
impl AtlasSearch<Compound> {
    /**The compound operator combines two or more operators into a single query.
    Each element of a compound query is called a clause, and each clause
    consists of one or more sub-queries.
    */
    ///
    ///For more details, see the [compound operator reference](https://www.mongodb.com/docs/atlas/atlas-search/compound/).
    pub fn compound() -> Self {
        AtlasSearch {
            name: "compound",
            stage: doc! {},
            _t: PhantomData,
        }
    }
    #[allow(missing_docs)]
    pub fn must<T>(mut self, must: impl IntoIterator<Item = AtlasSearch<T>>) -> Self {
        self.stage.insert(
            "must",
            must.into_iter().map(Document::from).collect::<Vec<_>>(),
        );
        self
    }
    #[allow(missing_docs)]
    pub fn must_not<T>(mut self, must_not: impl IntoIterator<Item = AtlasSearch<T>>) -> Self {
        self.stage.insert(
            "mustNot",
            must_not.into_iter().map(Document::from).collect::<Vec<_>>(),
        );
        self
    }
    #[allow(missing_docs)]
    pub fn should<T>(mut self, should: impl IntoIterator<Item = AtlasSearch<T>>) -> Self {
        self.stage.insert(
            "should",
            should.into_iter().map(Document::from).collect::<Vec<_>>(),
        );
        self
    }
    #[allow(missing_docs)]
    pub fn filter<T>(mut self, filter: impl IntoIterator<Item = AtlasSearch<T>>) -> Self {
        self.stage.insert(
            "filter",
            filter.into_iter().map(Document::from).collect::<Vec<_>>(),
        );
        self
    }
    #[allow(missing_docs)]
    pub fn minimum_should_match(mut self, minimum_should_match: i32) -> Self {
        self.stage
            .insert("minimumShouldMatch", minimum_should_match);
        self
    }
    #[allow(missing_docs)]
    pub fn score(mut self, score: Document) -> Self {
        self.stage.insert("score", score);
        self
    }
}
