[profile.default]
test-threads = 1
default-filter = 'not test(test::happy_eyeballs) and not test(kms_retry) and not test(atlas_connectivity)'

[profile.ci]
failure-output = "final"
test-threads = 1
fail-fast = false
default-filter = 'not test(test::happy_eyeballs) and not test(atlas_connectivity)'

[profile.ci.junit]
path = "junit.xml"
