tasks:
  - name: compile-on-latest
    commands:
      - func: "compile only"

  - name: compile-on-msrv
    commands:
      - func: "compile only"
        vars:
          # Our minimum supported Rust version. This should be updated whenever the MSRV is bumped.
          RUST_VERSION: 1.88.0

  - name: check-cargo-deny
    commands:
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env: [PROJECT_DIRECTORY]
          binary: bash
          args: [.evergreen/check-cargo-deny.sh]

  - name: check-rustfmt
    tags: [lint]
    commands:
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env: [PROJECT_DIRECTORY]
          binary: bash
          args: [.evergreen/check-rustfmt.sh]

  - name: check-clippy
    tags: [lint]
    commands:
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env: [PROJECT_DIRECTORY]
          binary: bash
          script: [.evergreen/check-clippy.sh]

  - name: check-semgrep
    tags: [lint]
    commands:
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env:
            - DRIVERS_TOOLS
            - PROJECT_DIRECTORY
            - MONGOCRYPT_LIB_DIR
          binary: bash
          args:
            - .evergreen/check-semgrep.sh

  - name: check-rustdoc
    tags: [lint]
    commands:
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env:
            - PROJECT_DIRECTORY
            - MONGOCRYPT_LIB_DIR
            - LD_LIBRARY_PATH
          binary: bash
          args: [.evergreen/check-rustdoc.sh]

  - name: test-rustdoc
    tags: [lint]
    commands:
      - func: "install libmongocrypt"
      - command: subprocess.exec
        type: test
        params:
          working_dir: src
          include_expansions_in_env:
            - DRIVERS_TOOLS
            - PROJECT_DIRECTORY
            - MONGOCRYPT_LIB_DIR
            - LD_LIBRARY_PATH
          binary: bash
          args:
            - .evergreen/run-rustdoc-tests.sh

functions:
  "compile only":
    - command: shell.exec
      type: test
      params:
        working_dir: src
        shell: bash
        script: |
          ${PREPARE_SHELL}
          RUST_VERSION=${RUST_VERSION} .evergreen/compile-only.sh
