task_groups:
  - name: azure-kms-task-group
    setup_group_can_fail_task: true
    setup_group_timeout_secs: 1800 # 30 minutes
    setup_group:
      - func: "fetch source"
      - func: "create expansions"
      - func: "prepare resources"
      - func: "windows fix"
      - func: "fix absolute paths"
      - func: "init test-results"
      - func: "make files executable"
      - func: "install rust"
      - func: "install libmongocrypt"
      - command: ec2.assume_role
        params:
          role_arn: ${aws_test_secrets_role}
      - command: subprocess.exec
        params:
          binary: bash
          args:
            - ${DRIVERS_TOOLS}/.evergreen/csfle/azurekms/create-and-setup-vm.sh
          env:
            AZUREKMS_VMNAME_PREFIX: RUST
          include_expansions_in_env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
    teardown_group:
      - command: subprocess.exec
        params:
          binary: bash
          args:
            - ${DRIVERS_TOOLS}/.evergreen/csfle/azurekms/delete-vm.sh
    tasks:
      - test-azure-kms

  - name: gcp-kms-task-group
    setup_group_can_fail_task: true
    setup_group_timeout_secs: 1800 # 30 minutes
    setup_group:
      - func: "fetch source"
      - func: "create expansions"
      - func: "prepare resources"
      - func: "windows fix"
      - func: "fix absolute paths"
      - func: "init test-results"
      - func: "make files executable"
      - func: "install rust"
      - func: "install libmongocrypt"
      - command: ec2.assume_role
        params:
          role_arn: ${aws_test_secrets_role}
      - command: subprocess.exec
        params:
          binary: bash
          args:
            - ${DRIVERS_TOOLS}/.evergreen/csfle/gcpkms/create-and-setup-instance.sh
          include_expansions_in_env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
    teardown_group:
      - command: subprocess.exec
        params:
          binary: bash
          args:
            - ${DRIVERS_TOOLS}/.evergreen/csfle/gcpkms/teardown.sh
    tasks:
      - test-gcp-kms

tasks:
  - name: test-gcp-kms
    commands:
      - command: subprocess.exec
        type: test
        params:
          binary: bash
          working_dir: src
          args:
            - .evergreen/run-gcp-kms-test.sh
          include_expansions_in_env:
            - PROJECT_DIRECTORY
            - DRIVERS_TOOLS
            - MONGOCRYPT_LIB_DIR
            - LD_LIBRARY_PATH

  - name: test-azure-kms
    commands:
      - command: subprocess.exec
        type: test
        params:
          binary: bash
          working_dir: src
          args:
            - .evergreen/run-azure-kms-test.sh
          include_expansions_in_env:
            - PROJECT_DIRECTORY
            - DRIVERS_TOOLS
            - MONGOCRYPT_LIB_DIR
            - LD_LIBRARY_PATH
