---

name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'There has not been any recent activity on this ticket, so we are marking it as stale. If we do not hear anything further from you, this issue will be automatically closed in one week.'
          days-before-issue-stale: 7
          days-before-pr-stale: -1
          days-before-close: 7
          close-issue-message: 'There has not been any recent activity on this ticket, so we are closing it. Thanks for reaching out and please feel free to file a new issue if you have further questions.'
          only-issue-labels: 'waiting-for-reporter'
